services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_vk:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin
    volumes:
      - redis_data_vk:/data
    command: ["redis-server", "--requirepass", "admin"]

  minio: 
    image:
      quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment: 
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data_vk:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
    ports:
      - "8080:8080" 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: >
      centrifugo
      -c /centrifugo/config.json
    ports:
      - "8090:8000"
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json:ro
    restart: unless-stopped



volumes:
  postgres_data_vk:
  redis_data_vk:
  minio_data_vk: