services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_vk:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin
    volumes:
      - redis_data_vk:/data
    command: ["redis-server", "--requirepass", "admin"]

  minio: 
    image:
      quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment: 
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data_vk:/data
    command: server /data --console-address ":9001"



volumes:
  postgres_data_vk:
  redis_data_vk:
  minio_data_vk: